sudo: false
language: python3


deploy:
  provider: gae
  keyfile: "jtcressy-c384e5039c0b.json"
  project: "jtcressy"
  default: true
  on: master

before_install:

  - openssl aes-256-cbc -K $encrypted_8713ba0e54f4_key -iv $encrypted_8713ba0e54f4_iv
    -in jtcressy-c384e5039c0b.json.enc -out jtcressy-c384e5039c0b.json -d

install:
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest -q test.py